name: Sync Labels

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Labels
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labels.yml
